# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:           pretty

# Setup
title:               Guides
description:         "My github pages"
tagline:             .
url:                 https://nicholashew.github.io/guides/
authors:            "nicholashew@users.noreply.github.com"

# Custom variables
repo:                 "https://github.com/nicholashew/guides"

plugins:
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Jekyll sass/scss minification.
sass:
  sass_dir:         _scss
  style:            compressed

toc:
  min_level:        2
  max_level:        4
