# Syntax highlighting
highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
title:               Guides
tagline:             .
url:                 https://nicholashew.github.io/guides/
baseurl:             ""

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

toc:
  min_level:        2
  max_level:        4