# Syntax highlighting
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:               Guides
tagline:             .
url:                 https://nicholashew.github.io/guides/

plugins:
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Jekyll sass/scss minification.
sass:
  sass_dir:         _scss
  style:            compressed

toc:
  min_level:        2
  max_level:        4
